export const wine = [
  // Seafood
  {
    name: 'Pichler-Krutzler Kellerberg Riesling',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Thunfisch',
    tag: ['Seafood', 'Thunfisch', 'Trocken'],
    src: '/wine/Vincent-Dereuil.png',
  },
  {
    name: 'Escarpment Kupe Pinot Noir',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Rotwein',
    pairsWith: 'Lachs',
    tag: ['Lachs'],
  },
  {
    name: 'Luis Seabra Granito Cru Alvarinho',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Muscheln',
    tag: ['Muscheln'],
  },
  {
    name: 'Laporte La Comtesse Sancerre',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Hummer',
    tag: ['Hummer'],
  },
  {
    name: 'Blanc de Blancs Premier Cru Champagne',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Schaumwein',
    pairsWith: 'Krabben',
    tag: ['Krabben'],
  },
  //   fleisch: [
  {
    name: 'Tabali Talinay Chardonnay',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Hähnchen',
    tag: ['Fleisch', 'Hähnchen'],
  },
  {
    name: 'Guerriero della Terra ',
    tasteProfile: ['Üppig', 'Trocken', 'Weich'],
    type: 'Rotwein',
    pairsWith: 'Ente',
    tag: ['Fleisch', 'Ente'],
  },
  {
    name: 'Bottega Gold',
    tasteProfile: ['Leicht', 'Sprudelnd', 'Säuerlich'],
    type: 'Schaumwein',
    pairsWith: 'Schwein',
    tag: ['Fleisch', 'Schwein'],
  },
  {
    name: 'Schola Sarmenti Cubardi Primitivo',
    tasteProfile: ['Üppig', 'Süß', 'Weich'],
    type: 'Rotwein',
    pairsWith: 'Lamm',
    tag: ['Fleisch', 'Lamm'],
  },
  {
    name: 'Constantia Glen Five',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Rotwein',
    pairsWith: 'Rind',
    tag: ['Fleisch', 'Rind'],
  },
  //   vegetarisch: [
  {
    name: 'Laberinto Sauvignon Blanc',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Salat',
    tag: ['Vegetarisch', 'Salat'],
  },
  {
    name: 'Bernardus Chardonnay',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Kartoffeln',
    tag: ['Vegetarisch', 'Kartoffeln'],
  },
  {
    name: 'Markowitsch Redmont',
    tasteProfile: ['Üppig', 'Süß', 'Weich'],
    type: 'Rotwein',
    pairsWith: 'Pilze',
    tag: ['Vegetarisch', 'Pilze'],
  },
  {
    name: 'Brookdale Estate Chenin Blanc',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Rotwein',
    pairsWith: 'Chillis',
    tag: ['Vegetarisch', 'Chillis'],
  },
  {
    name: 'Vie di Romans Chardonnay',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Pasta',
    tag: ['Vegetarisch', 'Pasta'],
  },

  //   käse: [
  {
    name: 'Little Beauty Sauvignon Blanc',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Ziegenkäse',
    tag: ['Käse', 'Ziegenkäse'],
  },
  {
    name: 'Llopart Ex Vite Brut Cava',
    tasteProfile: ['Üppig', 'Sprudelnd', 'Säuerlich'],
    type: 'Schaumwein',
    pairsWith: 'Parmesan',
    tag: ['Käse', 'Parmesan'],
  },
  {
    name: 'Vietti Moscato d Asti',
    tasteProfile: ['Leicht', 'Weich', 'Zart'],
    type: 'Schaumwein',
    pairsWith: 'Cheddar',
    tag: ['Käse', 'Cheddar'],
  },
  {
    name: 'Château Rieussec Sauternes',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Dessertwein',
    pairsWith: 'Blauschimmel',
    tag: ['Käse', 'Blauschimmel'],
  },
  {
    name: 'Brannland Iscider',
    tasteProfile: ['Leicht', 'Süß', 'Weich'],
    type: 'Apfelwein',
    pairsWith: 'Brie',
    tag: ['Käse', 'Brie'],
  },

  //   nachtisch: [
  {
    name: 'Château Climens Barsac',
    tasteProfile: ['Üppig', 'Süß', 'Säuerlich'],
    type: 'Dessetwein',
    pairsWith: 'Früchte',
    tag: ['Nachtisch', 'Früchte'],
  },
  {
    name: 'Acquesi Asti',
    tasteProfile: ['Üppig', 'Weich', 'Zart'],
    type: 'Schaumwein',
    pairsWith: 'Schokolade',
    tag: ['Nachtisch', 'Schokolade'],
  },
  {
    name: 'Canti Moscato dAsti',
    tasteProfile: ['Leicht', 'Weich', 'Zart'],
    type: 'Schaumwein',
    pairsWith: 'Kuchen',
    tag: ['Nachtisch', 'Kuchen'],
  },
];
