export const wine = [
  // Seafood
  {
    name: 'Pichler-Krutzler Kellerberg Riesling',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Thunfisch',
    tag: ['Seafood', 'Thunfisch', 'Trocken'],
    src: '/wine/Pichler-Krutzler.png',
  },
  {
    name: 'Escarpment Kupe Pinot Noir',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Rotwein',
    pairsWith: 'Lachs',
    tag: ['Seafood', 'Lachs', 'Trocken'],
    src: '/wine/Escarpment Kupe Pinot Noir.png',
  },
  {
    name: 'Luis Seabra Granito Cru Alvarinho',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Muscheln',
    tag: ['Seafood', 'Muscheln', 'Trocken'],
    src: '/wine/Luis Seabra Granito Cru Alvarinho.png',
  },
  {
    name: 'Laporte La Comtesse Sancerre',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Hummer',
    tag: ['Seafood', 'Hummer', 'Trocken'],
    src: '/wine/Laporte La Comtesse Sancerre.png',
  },
  {
    name: 'Blanc de Blancs Premier Cru Champagne',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Schaumwein',
    pairsWith: 'Krabben',
    tag: ['Seafood', 'Krabben', 'Trocken'],
    src: '/wine/Blanc de Blancs Premier Cru Champagne.png',
  },
  //   fleisch: [
  {
    name: 'Tabali Talinay Chardonnay',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Hähnchen',
    tag: ['Fleisch', 'Hähnchen', 'Trocken'],
    src: '/wine/Tabali Talinay Chardonnay.png',
  },
  {
    name: 'Guerriero della Terra',
    tasteProfile: ['Üppig', 'Trocken', 'Weich'],
    type: 'Rotwein',
    pairsWith: 'Ente',
    tag: ['Fleisch', 'Ente', 'Trocken'],
    src: '/wine/Guerriero della Terra.png',
  },
  {
    name: 'Prunotto Bansella Nizza 2019',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Rotwein',
    pairsWith: 'Schwein',
    tag: ['Fleisch', 'Schwein', 'Trocken'],
    src: '/wine/Prunotto Bansella Nizza 2019.png',
  },
  {
    name: 'Schola Sarmenti Cubardi Primitivo',
    tasteProfile: ['Üppig', 'Süß', 'Weich'],
    type: 'Rotwein',
    pairsWith: 'Lamm',
    tag: ['Fleisch', 'Lamm', 'Süß'],
    src: '/wine/Schola Sarmenti Cubardi Primitivo.png',
  },
  {
    name: 'Constantia Glen Five',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Rotwein',
    pairsWith: 'Rind',
    tag: ['Fleisch', 'Rind', 'Trocken'],
    src: '/wine/Constantia Glen Five.png',
  },
  //   vegetarisch: [
  {
    name: 'Laberinto Sauvignon Blanc',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Salat',
    tag: ['Vegetarisch', 'Salat', 'Trocken'],
    src: '/wine/Laberinto Sauvignon Blanc.png',
  },
  {
    name: 'Bernardus Chardonnay',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Kartoffeln',
    tag: ['Vegetarisch', 'Kartoffeln', 'Trocken'],
    src: '/wine/Bernardus Chardonnay.png',
  },
  {
    name: 'Markowitsch Redmont',
    tasteProfile: ['Üppig', 'Süß', 'Weich'],
    type: 'Rotwein',
    pairsWith: 'Pilze',
    tag: ['Vegetarisch', 'Pilze', 'Süß'],
    src: '/wine/Markowitsch Redmont.png',
  },
  {
    name: 'Brookdale Estate Chenin Blanc',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Chillis',
    tag: ['Vegetarisch', 'Chillis', 'Trocken'],
    src: '/wine/Brookdale Estate Chenin Blanc.png',
  },
  {
    name: 'Vie di Romans Chardonnay',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Pasta',
    tag: ['Vegetarisch', 'Pasta', 'Trocken'],
    src: '/wine/Vie di Romans Chardonnay.png',
  },

  //   käse: [
  {
    name: 'Little Beauty Sauvignon Blanc',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Ziegenkäse',
    tag: ['Käse', 'Ziegenkäse', 'Trocken'],
    src: '/wine/Little Beauty Sauvignon Blanc.png',
  },
  {
    name: 'Billaud-Simon Chablis Tête dOr',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Parmesan',
    tag: ['Käse', 'Parmesan', 'Trocken'],
    src: '/wine/Billaud-Simon Chablis Tête dOr.png',
  },
  {
    name: 'Tramin Stoan',
    tasteProfile: ['Üppig', 'Trocken', 'Säurehaltig'],
    type: 'Weißwein',
    pairsWith: 'Cheddar',
    tag: ['Käse', 'Cheddar', 'Trocken'],
    src: '/wine/Tramin Stoan.png',
  },
  {
    name: 'Château Rieussec Sauternes',
    tasteProfile: ['Üppig', 'Süß', 'Säuerlich'],
    type: 'Dessertwein',
    pairsWith: 'Blauschimmel',
    tag: ['Käse', 'Blauschimmel', 'Süß'],
    src: '/wine/Château Rieussec Sauternes.png',
  },
  {
    name: 'Brännland Iscider',
    tasteProfile: ['Leicht', 'Süß', 'Weich'],
    type: 'Apfelwein',
    pairsWith: 'Brie',
    tag: ['Käse', 'Brie', 'Süß'],
    src: '/wine/Brännland Iscider.png',
  },

  //   nachtisch: [
  {
    name: 'Familia Torres Viña Esmeralda',
    tasteProfile: ['Leicht', 'Süß', 'Säuerlich'],
    type: 'Dessetwein',
    pairsWith: 'Früchte',
    tag: ['Nachtisch', 'Früchte', 'Süß'],
    src: '/wine/Familia Torres Viña Esmeralda.png',
  },
  {
    name: 'Acquesi Asti',
    tasteProfile: ['Üppig', 'Süß', 'Zart'],
    type: 'Schaumwein',
    pairsWith: 'Schokolade',
    tag: ['Nachtisch', 'Schokolade', 'Süß'],
    src: '/wine/Acquesi Asti.png',
  },
  {
    name: 'Canti Moscato dAsti',
    tasteProfile: ['Leicht', 'Süß', 'Zart'],
    type: 'Schaumwein',
    pairsWith: 'Kuchen',
    tag: ['Nachtisch', 'Kuchen', 'Süß'],
    src: '/wine/Canti Moscato dAsti.png',
  },
];
