export const wine = [
  // Seafood
  {
    name: 'Pichler-Krutzler Kellerberg Riesling',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Thunfisch',
    tag: ['Seafood', 'Thunfisch', 'Trocken'],
    src: '/wine/Pichler-Krutzler.png',
  },
  {
    name: 'Château La Bertrande Cadillac',
    tasteProfile: ['Üppig', 'Süß', 'Säuerlich'],
    type: 'Dessertwein',
    pairsWith: 'Thunfisch',
    tag: ['Seafood', 'Thunfisch', 'Süß'],
    src: '/wine/Château La Bertrande Cadillac.png',
  },
  {
    name: 'Escarpment Kupe Pinot Noir',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Rotwein',
    pairsWith: 'Lachs',
    tag: ['Seafood', 'Lachs', 'Trocken'],
    src: '/wine/Escarpment Kupe Pinot Noir.png',
  },
  {
    name: 'Cazes Rivesaltes Ambré Vin Doux Naturel',
    tasteProfile: ['Leicht', 'Süß', 'Säuerlich'],
    type: 'Likörwein',
    pairsWith: 'Lachs',
    tag: ['Seafood', 'Lachs', 'Süß'],
    src: '/wine/Cazes Rivesaltes Ambré Vin Doux Naturel.png',
  },
  {
    name: 'Luis Seabra Granito Cru Alvarinho',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Muscheln',
    tag: ['Seafood', 'Muscheln', 'Trocken'],
    src: '/wine/Luis Seabra Granito Cru Alvarinho.png',
  },
  {
    name: 'Planeta Passito di Noto',
    tasteProfile: ['Üppig', 'Süß', 'Weich'],
    type: 'Dessertwein',
    pairsWith: 'Muscheln',
    tag: ['Seafood', 'Muscheln', 'Süß'],
    src: '/wine/Planeta Passito di Noto.png',
  },
  {
    name: 'Laporte La Comtesse Sancerre',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Hummer',
    tag: ['Seafood', 'Hummer', 'Trocken'],
    src: '/wine/Laporte La Comtesse Sancerre.png',
  },
  {
    name: 'Roccolo Grassi La Broia Recioto di Soave',
    tasteProfile: ['Üppig', 'Süß', 'Säuerlich'],
    type: 'Dessertwein',
    pairsWith: 'Hummer',
    tag: ['Seafood', 'Hummer', 'Süß'],
    src: '/wine/Roccolo Grassi La Broia Recioto di Soave.png',
  },
  {
    name: 'Blanc de Blancs Premier Cru Champagne',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Schaumwein',
    pairsWith: 'Krabben',
    tag: ['Seafood', 'Krabben', 'Trocken'],
    src: '/wine/Blanc de Blancs Premier Cru Champagne.png',
  },
  {
    name: 'Firriato L Ecrù Sicilia Passito',
    tasteProfile: ['Üppig', 'Süß', 'Weich'],
    type: 'Dessertwein',
    pairsWith: 'Krabben',
    tag: ['Seafood', 'Krabben', 'Süß'],
    src: '/wine/Firriato L Ecrù Sicilia Passito.png',
  },
  //   fleisch:
  {
    name: 'Tabali Talinay Chardonnay',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Hähnchen',
    tag: ['Fleisch', 'Hähnchen', 'Trocken'],
    src: '/wine/Tabali Talinay Chardonnay.png',
  },
  {
    name: 'Guerrieri L Amico Ciliegia',
    tasteProfile: ['Üppig', 'Süß', 'Weich'],
    type: 'Dessertwein',
    pairsWith: 'Hähnchen',
    tag: ['Fleisch', 'Hähnchen', 'Süß'],
    src: '/wine/Guerrieri L Amico Ciliegia',
  },
  {
    name: 'Guerriero della Terra',
    tasteProfile: ['Üppig', 'Trocken', 'Weich'],
    type: 'Rotwein',
    pairsWith: 'Ente',
    tag: ['Fleisch', 'Ente', 'Trocken'],
    src: '/wine/Guerriero della Terra.png',
  },
  {
    name: 'Bread & Butter Pinot Noir',
    tasteProfile: ['Üppig', 'Süß', 'Weich'],
    type: 'Rotwein',
    pairsWith: 'Ente',
    tag: ['Fleisch', 'Ente', 'Süß'],
    src: '/wine/Bread & Butter Pinot Noir.png',
  },
  {
    name: 'Prunotto Bansella Nizza 2019',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Rotwein',
    pairsWith: 'Schwein',
    tag: ['Fleisch', 'Schwein', 'Trocken'],
    src: '/wine/Prunotto Bansella Nizza 2019.png',
  },
  {
    name: 'El Principal Calicanto',
    tasteProfile: ['Üppig', 'Süß', 'Weich'],
    type: 'Rotwein',
    pairsWith: 'Schwein',
    tag: ['Fleisch', 'Schwein', 'Süß'],
    src: '/wine/El Principal Calicanto.png',
  },
  {
    name: 'Schola Sarmenti Cubardi Primitivo',
    tasteProfile: ['Üppig', 'Süß', 'Weich'],
    type: 'Rotwein',
    pairsWith: 'Lamm',
    tag: ['Fleisch', 'Lamm', 'Süß'],
    src: '/wine/Schola Sarmenti Cubardi Primitivo.png',
  },
  {
    name: 'Quinta do Paral Vinhas Velhas Tinto',
    tasteProfile: ['Üppig', 'Trocken', 'Weich'],
    type: 'Rotwein',
    pairsWith: 'Lamm',
    tag: ['Fleisch', 'Lamm', 'Trocken'],
    src: '/wine/Quinta do Paral Vinhas Velhas Tinto.png',
  },
  {
    name: 'Constantia Glen Five',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Rotwein',
    pairsWith: 'Rind',
    tag: ['Fleisch', 'Rind', 'Trocken'],
    src: '/wine/Constantia Glen Five.png',
  },
  {
    name: 'Ferreira Late Bottled Vintage Port',
    tasteProfile: ['Leicht', 'Süß', 'Weich'],
    type: 'Likörwein',
    pairsWith: 'Rind',
    tag: ['Fleisch', 'Rind', 'Süß'],
    src: '/wine/Ferreira Late Bottled Vintage Port.png',
  },
  //   vegetarisch:
  {
    name: 'Laberinto Sauvignon Blanc',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Salat',
    tag: ['Vegetarisch', 'Salat', 'Trocken'],
    src: '/wine/Laberinto Sauvignon Blanc.png',
  },
  {
    name: 'Keermont Fleurfontein',
    tasteProfile: ['Leicht', 'Süß', 'Säuerlich'],
    type: 'Dessertwein',
    pairsWith: 'Salat',
    tag: ['Vegetarisch', 'Salat', 'Süß'],
    src: '/wine/Keermont Fleurfontein.png',
  },
  {
    name: 'Bernardus Chardonnay',
    tasteProfile: ['Üppig', 'Süß', 'Weich'],
    type: 'Weißwein',
    pairsWith: 'Kartoffeln',
    tag: ['Vegetarisch', 'Kartoffeln', 'Süß'],
    src: '/wine/Bernardus Chardonnay.png',
  },
  {
    name: 'Colosi Passito',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Kartoffeln',
    tag: ['Vegetarisch', 'Kartoffeln', 'Trocken'],
    src: '/wine/Colosi Passito.png',
  },
  {
    name: 'Markowitsch Redmont',
    tasteProfile: ['Üppig', 'Süß', 'Weich'],
    type: 'Rotwein',
    pairsWith: 'Pilze',
    tag: ['Vegetarisch', 'Pilze', 'Süß'],
    src: '/wine/Markowitsch Redmont.png',
  },
  {
    name: 'Gesellmann Opus Eximium',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Rotwein',
    pairsWith: 'Pilze',
    tag: ['Vegetarisch', 'Pilze', 'Trocken'],
    src: '/wine/Gesellmann Opus Eximium.png',
  },
  {
    name: 'Brookdale Estate Chenin Blanc',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Chillis',
    tag: ['Vegetarisch', 'Chillis', 'Trocken'],
    src: '/wine/Brookdale Estate Chenin Blanc.png',
  },
  {
    name: 'Bernardins Muscat de Beaumes de Venise',
    tasteProfile: ['Leicht', 'Süß', 'Säuerlich'],
    type: 'Likörwein',
    pairsWith: 'Chillis',
    tag: ['Vegetarisch', 'Chillis', 'Süß'],
    src: '/wine/Bernardins Muscat de Beaumes de Venise.png',
  },
  {
    name: 'Vie di Romans Chardonnay',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Pasta',
    tag: ['Vegetarisch', 'Pasta', 'Trocken'],
    src: '/wine/Vie di Romans Chardonnay.png',
  },
  {
    name: 'Epicuro Susumaniello',
    tasteProfile: ['Üppig', 'Süß', 'Weich'],
    type: 'Rotwein',
    pairsWith: 'Pasta',
    tag: ['Vegetarisch', 'Pasta', 'Süß'],
    src: '/wine/Epicuro Susumaniello.png',
  },

  //   käse:
  {
    name: 'Little Beauty Sauvignon Blanc',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Ziegenkäse',
    tag: ['Käse', 'Ziegenkäse', 'Trocken'],
    src: '/wine/Little Beauty Sauvignon Blanc.png',
  },
  {
    name: 'Domäne Wachau V.D.N Grüner Veltliner',
    tasteProfile: ['Üppig', 'Süß', 'Säuerlich'],
    type: 'Likörwein',
    pairsWith: 'Ziegenkäse',
    tag: ['Käse', 'Ziegenkäse', 'Süß'],
    src: '/wine/Domäne Wachau V.D.N Grüner Veltliner.png',
  },
  {
    name: 'Billaud-Simon Chablis Tête dOr',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Parmesan',
    tag: ['Käse', 'Parmesan', 'Trocken'],
    src: '/wine/Billaud-Simon Chablis Tête dOr.png',
  },
  {
    name: 'Coume del Mas Galateo Banyuls',
    tasteProfile: ['Üppig', 'Süß', 'Weich'],
    type: 'Likörwein',
    pairsWith: 'Parmesan',
    tag: ['Käse', 'Parmesan', 'Süß'],
    src: '/wine/Coume del Mas Galateo Banyuls.png',
  },
  {
    name: 'Tramin Stoan',
    tasteProfile: ['Üppig', 'Trocken', 'Säurehaltig'],
    type: 'Weißwein',
    pairsWith: 'Cheddar',
    tag: ['Käse', 'Cheddar', 'Trocken'],
    src: '/wine/Tramin Stoan.png',
  },
  {
    name: 'Lustau San Emilio Pedro Ximenez',
    tasteProfile: ['Üppig', 'Süß', 'Säurehaltig'],
    type: 'Likörwein',
    pairsWith: 'Cheddar',
    tag: ['Käse', 'Cheddar', 'Süß'],
    src: '/wine/Lustau San Emilio Pedro Ximenez.png',
  },
  {
    name: 'Château Rieussec Sauternes',
    tasteProfile: ['Üppig', 'Süß', 'Säuerlich'],
    type: 'Dessertwein',
    pairsWith: 'Blauschimmel',
    tag: ['Käse', 'Blauschimmel', 'Süß'],
    src: '/wine/Château Rieussec Sauternes.png',
  },
  {
    name: 'Montonale Orestilla',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Blauschimmel',
    tag: ['Käse', 'Blauschimmel', 'Trocken'],
    src: '/wine/Montonale Orestilla.png',
  },
  {
    name: 'Brännland Iscider',
    tasteProfile: ['Leicht', 'Süß', 'Weich'],
    type: 'Apfelwein',
    pairsWith: 'Brie',
    tag: ['Käse', 'Brie', 'Süß'],
    src: '/wine/Brännland Iscider.png',
  },
  {
    name: 'Mosi Wines Tinashe Chenin',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Brie',
    tag: ['Käse', 'Brie', 'Trocken'],
    src: '/wine/Mosi Wines Tinashe Chenin.png',
  },

  //   nachtisch:
  {
    name: 'Familia Torres Viña Esmeralda',
    tasteProfile: ['Leicht', 'Süß', 'Säuerlich'],
    type: 'Dessetwein',
    pairsWith: 'Früchte',
    tag: ['Nachtisch', 'Früchte', 'Süß'],
    src: '/wine/Familia Torres Viña Esmeralda.png',
  },
  {
    name: 'Nitída Coronata Integration',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Früchte',
    tag: ['Nachtisch', 'Früchte', 'Trocken'],
    src: '/wine/Nitída Coronata Integration.png',
  },
  {
    name: 'Acquesi Asti',
    tasteProfile: ['Üppig', 'Süß', 'Zart'],
    type: 'Schaumwein',
    pairsWith: 'Schokolade',
    tag: ['Nachtisch', 'Schokolade', 'Süß'],
    src: '/wine/Acquesi Asti.png',
  },
  {
    name: 'Matassa Brutal Rouge',
    tasteProfile: ['Leicht', 'Trocken', 'Säuerlich'],
    type: 'Rotmwein',
    pairsWith: 'Schokolade',
    tag: ['Nachtisch', 'Schokolade', 'Trocken'],
    src: '/wine/Matassa Brutal Rouge.png',
  },
  {
    name: 'Canti Moscato dAsti',
    tasteProfile: ['Leicht', 'Süß', 'Zart'],
    type: 'Schaumwein',
    pairsWith: 'Kuchen',
    tag: ['Nachtisch', 'Kuchen', 'Süß'],
    src: '/wine/Canti Moscato dAsti.png',
  },
  {
    name: 'Dornier Donatus White',
    tasteProfile: ['Üppig', 'Trocken', 'Säuerlich'],
    type: 'Weißwein',
    pairsWith: 'Kuchen',
    tag: ['Nachtisch', 'Kuchen', 'Trocken'],
    src: '/wine/Dornier Donatus White.png',
  },
];
