import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Foodlist from '../First-Quizz-Page/Foodlist/FoodList';
import styled from 'styled-components';

export default function Home() {
  return (
    <>
      <Head>
        <title>In Vino Veritas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="header-picture.jpeg" href="/public/header-picture.jpeg" />
      </Head>

      <StyledMain>
        <Foodlist></Foodlist>
      </StyledMain>
    </>
  );
}

const StyledMain = styled.main`
  height: 100vh;
`;
